### PR TITLE
Handle tls.Conn handshake timeout

### LINKED ISSUE #161: server: simple tls.Listener can exhaust TCP resources
`ReadTimeout` and `WriteTimeout` timeouts are not reflected when a connection is `*tls.Conn`. This leads SMTPS server to wait for the TLS connection forever.

Reproducible with:
```
$ telnet localhost 465 # will hang forever
```

### PR DESCRIPTION
**Pull request by kayrus**
resolves #161

### CODE REVIEW

**Comment by emersion** [comment]
Does this happen because the handshake implicitly happens on first read or write? Would it fix it to set both read and write timeouts in `WriteResponse` and `ReadLine`, instead of just one of these?

**Comment by kayrus** [comment]
@emersion no, the wait happens during the TLS handshake and it is not related to `WriteResponse` or `ReadLine`. `greet` method is blocked by TLS handshake.

**Comment by kayrus** [comment]
@emersion unfortunately it is not handled. 
When I set this debug:

```
conn.go
+++ b/vendor/github.com/emersion/go-smtp/conn.go
@@ -956,6 +956,7 @@ func (c *Conn) greet() {
 func (c *Conn) WriteResponse(code int, enhCode EnhancedCode, text ...string) {
        // TODO: error handling
        if c.server.WriteTimeout != 0 {
+               fmt.Printnf("set timeout: %s\n", c.server.WriteTimeout)
                c.conn.SetWriteDeadline(time.Now().Add(c.server.WriteTimeout))
        }

````

it is triggered, but not reflected on plain TCP connection, when the listener is SMTPS:


```
set timeout: 5s
# nothing happens, connection is still open
```

See http code for an example: https://github.com/golang/go/blob/94323206aee1363471a4ae3b8d40dd4ae7a5cd9c/src/net/http/server.go#L1818-L1850

**Comment by emersion** [comment]
Try adding `SetReadDeadline` instead.

**Comment by kayrus** [comment]
@emersion I set both:
```
        smtpServer.ReadTimeout = 5 * time.Second
        smtpServer.WriteTimeout = 5 * time.Second
```

Doesn't help. Feel free to reproduce this bug in your local env.

**Comment by emersion** [comment]
No, what I mean is adding a `SetReadDeadline` call in `WriteResponse`. Have you tried this?

**Comment by kayrus** [comment]
@emersion yes, it works, but it doesn't expose the TLS handshake error

**Comment by kayrus** [comment]
@emersion what do you suggest then? add `SetReadDeadline` into the `WriteResponse` handler? From my point of view the https://github.com/golang/go/blob/94323206aee1363471a4ae3b8d40dd4ae7a5cd9c/src/net/http/server.go#L1818-L1836 approach looks cleaner.

**Comment by kayrus** [comment]
@emersion please put the io.EOF back. It causes issues on L4 level TCP monitoring.

**Comment by emersion** [comment]
Nack, EOF is a TLS handshake error like any other.

TBH, I'm not even sure why we log the handshake failures in `ErrorLog`. Other connection errors aren't logged there. We should only log panics in there. PRs welcome.

**Pull request merged**
