### PR TITLE
fix a data racing issue

### LINKED ISSUE #149: Possible data racing issue
Dear @emersion ,

I found a possible data racing issue and here's short sample code to reproduce it. PR will follow shortly.

```go
package main

import (
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/emersion/go-smtp"
)

type backend struct {}

func (be *backend) Login(_ *smtp.ConnectionState, username, password string) (smtp.Session, error) {

	return &Session{}, nil
}

func (be *backend) AnonymousLogin(_ *smtp.ConnectionState) (smtp.Session, error) {

	return &Session{}, nil
}

type Session struct{}

func (s *Session) AuthPlain(username, password string) error {
	if username != "username" || password != "password" {
		return errors.New("Invalid username or password")
	}
	return nil
}

func (s *Session) Mail(from string, opts smtp.MailOptions) error {
	log.Println("Mail from:", from)
	return nil
}

func (s *Session) Rcpt(to string) error {
	log.Println("Rcpt to:", to)
	return nil
}

func (s *Session) Data(r io.Reader) error {
	if b, err := ioutil.ReadAll(r); err != nil {
		return err
	} else {
		log.Println("Data:", string(b))
	}
	return nil
}

func (s *Session) Reset() {}

func (s *Session) Logout() error {
	return nil
}

func main() {
	be := &backend{}

	s := smtp.NewServer(be)

	s.Addr = ":1025"
	s.Domain = "localhost"
	s.ReadTimeout = 10 * time.Second
	s.WriteTimeout = 10 * time.Second
	s.MaxMessageBytes = 1024 * 1024
	s.MaxRecipients = 50
	s.AllowInsecureAuth = true

	exit := make(chan os.Signal)

	signal.Notify(exit, os.Interrupt, os.Kill)

	go func() {
		<-exit

		err := s.Close()
		if err != nil {
			log.Fatal("Failed in stopping smtp service: %s", err.Error())
		} else {
			fmt.Println("Stopped SMTP service.")
		}
	}()

	log.Println("Starting server at", s.Addr)
	if err := s.ListenAndServe(); err != nil {
		log.Fatal(err)
	}
}

```

Save the sample code as `main.go` and run it with `-race` argument:

```
go run -race main.go
```

Press Ctrl-C to abort and you will get error like below:
```
2021/07/21 22:54:19 Starting server at :1025
==================
WARNING: DATA RACE
Read at 0x00c0001740c8 by goroutine 8:
  github.com/emersion/go-smtp.(*Server).Close()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:233 +0xa4
  main.main.func1()
      C:/Users/John/Desktop/go-test/main.go:82 +0x4e

Previous write at 0x00c0001740c8 by main goroutine:
  github.com/emersion/go-smtp.(*Server).Serve()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:111 +0x14a
  github.com/emersion/go-smtp.(*Server).ListenAndServe()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:195 +0x10c
  main.main()
      C:/Users/John/Desktop/go-test/main.go:91 +0x2fa

Goroutine 8 (running) created at:
  main.main()
      C:/Users/John/Desktop/go-test/main.go:79 +0x27c
==================
==================
WARNING: DATA RACE
Read at 0x00c00010a730 by goroutine 8:
  github.com/emersion/go-smtp.(*Server).Close()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:233 +0x235
  main.main.func1()
      C:/Users/John/Desktop/go-test/main.go:82 +0x4e

Previous write at 0x00c00010a730 by main goroutine:
  github.com/emersion/go-smtp.(*Server).Serve()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:111 +0xf6
  github.com/emersion/go-smtp.(*Server).ListenAndServe()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:195 +0x10c
  main.main()
      C:/Users/John/Desktop/go-test/main.go:91 +0x2fa

Goroutine 8 (running) created at:
  main.main()
      C:/Users/John/Desktop/go-test/main.go:79 +0x27c
==================
==================
WARNING: DATA RACE
Read at 0x00c000120150 by goroutine 8:
  net.(*TCPListener).ok()
      C:/Program Files/Go/src/net/tcpsock_posix.go:137 +0x35
  net.(*TCPListener).Close()
      C:/Program Files/Go/src/net/tcpsock.go:272 +0x40
  github.com/emersion/go-smtp.(*Server).Close()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:234 +0x247
  main.main.func1()
      C:/Users/John/Desktop/go-test/main.go:82 +0x4e

Previous write at 0x00c000120150 by main goroutine:
  net.(*sysListener).listenTCP()
      C:/Program Files/Go/src/net/tcpsock_posix.go:173 +0x11b
  net.(*ListenConfig).Listen()
      C:/Program Files/Go/src/net/dial.go:639 +0x3bb
  net.Listen()
      C:/Program Files/Go/src/net/dial.go:712 +0x85
  github.com/emersion/go-smtp.(*Server).ListenAndServe()
      C:/Users/John/go/pkg/mod/github.com/emersion/go-smtp@v0.15.0/server.go:190 +0xd4
  main.main()
      C:/Users/John/Desktop/go-test/main.go:91 +0x2fa

Goroutine 8 (running) created at:
  main.main()
      C:/Users/John/Desktop/go-test/main.go:79 +0x27c
==================
Stopped SMTP service.
Found 3 data race(s)
exit status 66
```

### PR DESCRIPTION
**Pull request by ly020044**
fixes #149

### CODE REVIEW

**Review by foxcpp — APPROVED** [review]
LGTM

**Comment by jh125486** [comment]
Would it be possible to get a new tag (0.16) created to get this out?

**Comment by emersion** [comment]
Maybe would be nice to merge https://github.com/emersion/go-smtp/pull/148 for 0.16.

**Comment by iredmail** [comment]
`Backend` interface is now totally different and not backward compatible with 0.15.0, a new major release version (like v1, v2) should be tagged and not use `0.16`.

**Comment by emersion** [comment]
No, 0.x version can have breaking changes.

**Pull request merged**
