### PR TITLE
server: XCLIENT implementation

### PR DESCRIPTION
**Pull request by foxcpp**
Some interface details probably need discussion.

### CODE REVIEW

**Comment by emersion** [comment]
Hmm, this backend API is a little bit unfortunate. Would there be a way to only have a new `Session` method?

**Comment by foxcpp** [comment]
> Hmm, this backend API is a little bit unfortunate. Would there be a way to only have a new `Session` method?

It is due to the fact XCLIENT is valid both before and after AUTH and may work differently depending on authentication status. I initially thought about avoiding two methods by creating a session using anonymous callback but it may be problematic since backend may permit XCLIENT but not unauthenticated transactions and permit them after XCLIENT.  ( On a second though that setup does not really make a lot of sense, not sure... )

If I had the liberty of doing a major interface change I would ditch authentication-centered Session creation and add Auth() method to Session, create one session per connection and be done with it (we already have one session per connection but the way it is initially created is rather convoluted).

**Comment by emersion** [comment]
>If I had the liberty of doing a major interface change I would ditch authentication-centered Session creation and add Auth() method to Session, create one session per connection and be done with it (we already have one session per connection but the way it is initially created is rather convoluted).

Agreed. Do you think it's worth it to break the API this way?

**Comment by foxcpp** [comment]
I believe HAProxy's PROXY protocol is more widely supported therefore it is a good idea to implement it first.

**Comment by foxcpp** [comment]
It is also much more simple than XCLIENT which is SMTP-focused. It might be a good idea to support it too if we take into account SMTP-aware proxies.

**Comment by kayrus** [comment]
HAProxy's PROXY protocol is easy to implement using the https://github.com/pires/go-proxyproto package:
```
                        // Wrap listener in a proxyproto listener
                        proxyListener := &proxyproto.Listener{Listener: smtpListener}
                        err := smtpServer.Serve(proxyListener)
```

**Comment by foxcpp** [comment]
Closing as I do not intend to continue work on XCLIENT in foreseeable future.

**Comment by foxcpp** [comment]
After a more careful research I made the decision it is useful to support both PROXY and XCLIENT since XCLIENT is more flexible and is compatible with connection pooling while PROXY is not.

**Comment by xdkaka** [comment]
> HAProxy's PROXY protocol is easy to implement using the https://github.com/pires/go-proxyproto package:
> 
> ```
>                         // Wrap listener in a proxyproto listener
>                         proxyListener := &proxyproto.Listener{Listener: smtpListener}
>                         err := smtpServer.Serve(proxyListener)
> ```


In this way, is the proxy server able to forge the user's real IP?

**Pull request closed without merging**
