### PR TITLE
Add Noop method to the Session interface

### PR DESCRIPTION
**Pull request by kayrus**
And add error pointer to the Reset method

`Noop()` is supposed to be used to test the connection state

### CODE REVIEW

**Comment by emersion** [comment]
I'm not sure I understand:

- This PR just adds a new method but never calls it.
- `NOOP` always make the server reply with `OK` immediately. The backend doesn't need to be involved in this.

**Comment by emersion** [comment]
`Session` is a type used by servers only.

**Comment by kayrus** [comment]
It is used by proxy. Proxy is kinda client-server.

**Comment by emersion** [comment]
Sorry, I don't understand what you're trying to do, but I'm not going to merge this change, it doesn't make sense to me.

**Comment by kayrus** [comment]
@emersion Your questions don't make sense :\ This PR just extends the session interface. Session interface is used in https://github.com/emersion/go-smtp-proxy. Each session represents a connection. In order to keep running long living connections I need to periodically execute NOOP command. If the NOOP fails, the connection would be reestablished.

**Comment by kayrus** [comment]
@emersion I see you just archived the https://github.com/emersion/go-smtp-proxy repo. At least google cache shows that it was still active on 25th of April. Even though, I still would like to have a `Noop` method in upstream. I hope you can review the PR once again and merge it.

**Comment by emersion** [comment]
I don't have any more free time to spend on your issue.

**Pull request closed without merging**
