### PR TITLE
Store last SMTP code and message in Client

### PR DESCRIPTION
**Pull request by macrosonline**

### CODE REVIEW

**Comment by emersion** [comment]
What's the motivation for this?

**Comment by macrosonline** [comment]
> What's the motivation for this?

I need to get SMTP code when sending mails, to know "is that error temporary or not" or to get full smtp response when message is accepted (some systems shows internal message id in response and this id is required to debug delivery).

**Comment by emersion** [comment]
If there is an SMTP error, the returned error will be of type `smtp.SMTPError`.

**Comment by macrosonline** [comment]
> If there is an SMTP error, the returned error will be of type `smtp.SMTPError`.

But how about SMTP response message, especially if it is not error ?

**Comment by emersion** [comment]
Closing as duplicate of https://github.com/emersion/go-smtp/issues/189

**Pull request closed without merging**
