### PR TITLE
Auth check for mail, from, data commands #216

### PR DESCRIPTION
**Pull request by mukulsib**

### CODE REVIEW

**Comment by emersion** [comment]
Auth can be enabled _and_ optional for the backend.

**Comment by mukulsib** [comment]
> Auth can be enabled _and_ optional for the backend.

Hi @emersion 

Could you please guide me here? I tried explicitly setting the `AuthDisabled` to `false` but it still did not work.

**Comment by mukulsib** [comment]
Hi @emersion 

Request you to go through the issue for complete details [here](https://github.com/emersion/go-smtp/issues/216) and let me knoe if i have missed something, because its bit urgent for us. Thanks

**Comment by emersion** [comment]
Superseded by https://github.com/emersion/go-smtp/pull/222

**Pull request closed without merging**
