### PR TITLE
feat: adding the smtp auth login mechanism

### PR DESCRIPTION
**Pull request by buroa**
This is needed so I can finish writing unit tests for https://github.com/foxcpp/maddy/pull/683

### CODE REVIEW

**Comment by emersion** [comment]
Sorry, but I don't want to support the legacy LOGIN mechanism by default. Library users to register their own SASL mechanisms if they want to.

**Comment by buroa** [comment]
> Sorry, but I don't want to support the legacy LOGIN mechanism by default. Library users to register their own SASL mechanisms if they want to.

Are you fucking serious?

**Comment by buroa** [comment]
@emersion You need to get off of Github if you are not going to be open to conversations regarding open-source software. Closing issues within seconds of it being open is toxic. I'll make sure people know this when looking at your products in the future.

**Comment by emersion** [comment]
I don't believe closing pull requests for undesirable features is being toxic. I generally do leave pull requests opened when I am not 100% sure that the feature is undesirable, but this is not the case here, the topic at hand has been discussed before in the context of go-sasl and is well-understood.

Being an open-source maintainer doesn't mean that I _have to_ accept all features. I won't comment on the aggressive threat, that's enough for me, I do not wish to interact further with someone with your mindset.

**Pull request closed without merging**
