### PR TITLE
client: Restrict the line length for responses

### PR DESCRIPTION
**Pull request by foxcpp**
Intended to protect MTA implementations from malicious recipient servers.

I am not sure about the length limit value though, for Server it is
configurable via the MaxLineLength field, for Client I do not see a context
where it can be set. Or perhaps it is not really needed?

### CODE REVIEW

**Comment by emersion** [comment]
The RFC says the maximum length for replies is 512 bytes (https://tools.ietf.org/html/rfc5321#section-4.5.3.1.5). I'm fine with hardcoding this, at least for now.

**Comment by emersion** [comment]
Note, I just realized `textproto.Conn` has a `Reader` field, which has a `bufio.Reader` field, which allows us to set the maximum buffer size.

**Comment by foxcpp** [comment]
>bufio.Reader field, which allows us to set the maximum buffer size.

Does it? The only 'size' I see is in NewReaderSize which sets *minimal* buffer size.

Additionally, textproto.Conn.ReadLine* joins results of multiple R.Read calls so it is not limited by the bufio.Reader buffer (see readLineSlice implementation in net/textproto/reader.go)

**Comment by emersion** [comment]
>Does it? The only 'size' I see is in NewReaderSize which sets minimal buffer size.

Oh, I'm mistaken, I was thinking about `bufio.Scanner` instead.

**Pull request merged**
